import NavBar from "@/components/common/NavBar";
import "./globals.css";
import { Toaster } from "sonner";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* top nav bar */}
        <NavBar />
        {/* main content */}
        <main>
          {children}
          <Toaster
            richColors
            position="top-right"
          />
        </main>
        <Footer />
      </body>
    </html>
  );
}
